//ALERT
export const CAMBIAR_ESTADO_ERROR = 'CAMBIAR_ESTADO_ERROR';
//---------------------------------------------------------------------
//BOPLUS
export const PETICION_IMAGENES_RADIO = 'PETICION_IMAGENES_RADIO';
export const PETICION_IMAGENES_TV = 'PETICION_IMAGENES_TV';
export const PETICION_IMAGENES_ANUNCIO = 'PETICION_IMAGENES_ANUNCIO';
//DEFAULT
export const CARGAR_DEFAULT_PUBLICIDAD = 'CARGAR_DEFAULT_PUBLICIDAD';
//PETICION IMAGEN PRINCIPAL PUBLICIDAD
export const PETICION_PUBLICIDAD_PRINCIPAL = 'PETICION_PUBLICIDAD_PRINCIPAL';
//
export const PETICION_INFORMACION_QD = 'PETICION_INFORMACION_QD';
